[build]
  command = "npm ci && npm run build"
  publish = "dist/website/browser"

[build.environment]
  NODE_VERSION = "20"

# Angular router fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
