[build]
  base = "website"
  command = "npm ci && npm run build"
  # adjust if your angular.json outputPath differs
  publish = "dist/website"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
